.circleci/config.yml, Dockerfile, README.md
along with the Dockerflow circleci 2 build env
Closes #12
=> feat: add a Dockerfile based on debian stretch-slim

migrations/2018-02-20-220249_create_broadcastsv1_table/up.sql, src/db/models.rs, src/error.rs, src/http.rs, version.json
also add a created column alongside last_updated and other minor
changes
Closes #11
=> feat: add Dockerflow styled health/version checks

Rocket.toml, src/auth.rs, src/db/models.rs, src/error.rs, src/http.rs, src/main.rs
=> feat: handle auth via Bearer tokens

src/http.rs
inherit the database_url via RocketConfig::read
and test multiple auth tokens in http.rs
Closes #16
=> feat: cleanup Config usage

.travis.yml, Cargo.toml, README.md, src/auth.rs, src/db/mod.rs, src/db/models.rs, src/http.rs, src/main.rs
and a couple minor refactors
Closes #17
=> feat: use diesel's embedded migrations

src/error.rs, src/http.rs
also fix actual unauthorized responses to 403
Closes #21
=> feat: return WWW-Authenticate on 401s

.clog.toml, CONTRIBUTING.md, README.md
=> feat: add a .clog.toml and CONTRIBUTING.md

Dockerfile
=> feat: peg Docker build to rust nightly-2018-04-04

Cargo.lock, Cargo.toml, Dockerfile
also upgrade diesel
Closes #36
=> feat: upgrade to rocket 0.3.10

Cargo.lock, Cargo.toml, src/db/mod.rs, src/db/models.rs, src/error.rs, src/http.rs, src/logging.rs, src/main.rs
Closes #9 
~~If this looks good I'll break apart mozsvc-common and slog-mozlog-json from this PR into their own repos~~ Updated w/ their new crate references
=> feat: create a logging setup via slog/slog-mozlog-json

Cargo.lock, Dockerfile, docker-compose.yaml, src/logging.rs
also:
- include libssl in the Docker, needed for new log dependencies
- default json_logging to true for stage/prod
Closes #35, #43
=> feat: add a docker compose setup

.travis.yml, Cargo.lock, Cargo.toml, Dockerfile, src/auth.rs, src/error.rs, src/http.rs, src/main.rs
and bump to latest rocket/rust nightly
Closes #24
=> feat: validate the PUT input

.travis.yml, Cargo.lock, Dockerfile, src/error.rs, src/http.rs
and bump to latest rocket/nightly
Closes #46
=> feat: render a unique errno code per error

src/auth.rs, src/db/mod.rs, src/db/models.rs, src/error.rs, src/http.rs, src/logging.rs, src/main.rs
and some clippy cleanups/rust fmt
Closes #48
=> feat: warn log for ACL related errors

Dockerfile
(used for docker image verification)
=> chore: include /app/version.json per dockerflow

Dockerfile, src/auth.rs, src/db/models.rs, src/http.rs, src/main.rs
and default it in the Dockerfile
Closes #54
=> feat: hacky support of ROCKET_LOG=off

src/db/mod.rs, src/http.rs
and properly render their error responses (special casing heartbeat's
handling)
also add cargo fmt -- --check
Closes #59
=> fix: propagate db pool errors into HandlerErrors

README.md
=> feat: improve the README

Cargo.lock, Cargo.toml, src/logging.rs, src/main.rs
=> refactor: utilize slog_derive

src/logging.rs
=> fix: get_bool now returns ConfigError::Missing

Cargo.lock
=> chore: update deps per cargo audit

README.md
Issue https://github.com/mozilla-services/services-engineering/issues/3
=> chore: add a badge for the matrix channel

Cargo.lock, Cargo.toml
=> chore: Base to rocket "0.4"

Cargo.lock, Cargo.toml, Rocket.toml, src/http.rs, src/main.rs, src/metrics.rs, src/tags.rs
* note: this uses a semi-bastardized version of the metrics library from
syncstorage-rs. KV doesn't quite work right yet due to ownership
issues, but that's only for logging issues anyway.
=> feat: add metrics

rust-toolchain, src/http.rs
=> fix: oops, improve the health check

CHANGELOG.md, Cargo.lock, Cargo.toml
=> chore: tag 0.3.0
